# Generated by Django 3.2.1 on 2021-09-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Main Dishes', 'Main Dishes'), ('Kids Menus', 'Kids Menus'), ('Hot Baguette', 'Hot Baguette'), ('Burger Bar', 'Burger Bar')], db_index=True, default='others', max_length=14, verbose_name='Category'),
        ),
    ]
