# Generated by Django 3.2.4 on 2021-11-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
